
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flrqchzjwthgagdjiyhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZscnFjaHpqd3RoZ2FnZGppeWhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NjgzNTUsImV4cCI6MjA2NTQ0NDM1NX0.YoCPdrgd3mx1uoB7j4DloCTrDY77LxqFq1qWr3TGjFA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage, // Utilise localStorage pour la persistance
    persistSession: true, // Assure la persistance de la session
    autoRefreshToken: true, // Rafraîchit automatiquement le token
  },
});
